data_domain: graph
data_type: AQSOL
data_name: AQSOL
data_dir: datasets/${data_domain}/${data_type}
#data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${data_name}

# Dataset parameters
num_features: 1
num_classes: 1
task: classification
loss_type: cross_entropy
task_level: graph
