data_domain: graph
data_type: cocitation
data_name: citeseer
data_dir: datasets/${data_domain}/${data_type}
#data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${data_name}

# Dataset parameters
num_features: 3703
num_classes: 6
task: classification
loss_type: cross_entropy
monitor_metric: accuracy
task_level: node
