data_domain: graph
data_type: TUDataset
data_name: PROTEINS
data_dir: datasets/${data_domain}/${data_type}
#data_split_dir: ${oc.env:PROJECT_ROOT}/datasets/data_splits/${data_name}

# Dataset parameters
num_features: 3 # here basically I specify the initial num features in PROTEINS at x aka x_0
num_classes: 2
task: classification
loss_type: cross_entropy
monitor_metric: accuracy
task_level: graph

